{
  "errors": [
    {
      "id": 1,
      "name": "Error",
      "message": "this is a general error",
      "stack": "Error: this is a general error\n    at AppComponent.webpackJsonp.190.AppComponent.error1 (http://localhost:8080/bundles/app.32d9c4805f0c63f93399.bundle.js:36819:15)\n    at Object.eval [as handleEvent] (ng:///AppModule/AppComponent.ngfactory.js:68:31)\n    at handleEvent (http://localhost:8080/bundles/vendor.32d9c4805f0c63f93399.bundle.js:28168:155)\n    at callWithDebugContext (http://localhost:8080/bundles/vendor.32d9c4805f0c63f93399.bundle.js:29677:42)\n    at Object.debugHandleEvent [as handleEvent] (http://localhost:8080/bundles/vendor.32d9c4805f0c63f93399.bundle.js:29264:12)\n    at dispatchEvent (http://localhost:8080/bundles/vendor.32d9c4805f0c63f93399.bundle.js:24580:25)\n    at http://localhost:8080/bundles/vendor.32d9c4805f0c63f93399.bundle.js:25205:38\n    at HTMLButtonElement.<anonymous> (http://localhost:8080/bundles/vendor.32d9c4805f0c63f93399.bundle.js:11801:53)\n    at ZoneDelegate.invokeTask (http://localhost:8080/bundles/polyfills.32d9c4805f0c63f93399.bundle.js:13176:31)\n    at Object.onInvokeTask (http://localhost:8080/bundles/vendor.32d9c4805f0c63f93399.bundle.js:19360:33)",
      "headers": "",
      "createdOn": "2018-01-24T14:03:02.802Z"
    },
    {
      "id": 2,
      "name": "HttpErrorResponse",
      "message": "Http failure response for (unknown url): 0 Unknown Error",
      "stack": "",
      "status": 0,
      "statusText": "Unknown Error",
      "url": null,
      "headers": "",
      "createdOn": "2018-01-24T14:03:09.290Z"
    }
  ]
}